### ISSUE TITLE
netwoker stop有点问题

### ISSUE THREAD

**Issue by erdong01** [bobohume/gonet#17]
https://github.com/bobohume/gonet/blob/master/network/ServerSocketClient.go

func (s *ServerSocketClient) Stop() bool {
	timer.RegisterTimer(s.timerId, timer.TICK_INTERVAL, func() {
		timer.StopTimer(s.timerId)
		if atomic.CompareAndSwapInt32(&s.state, SSF_RUN, SSF_STOP) {
			if s.conn != nil {
				s.conn.Close()
			}
		}
	})
	return false
}
Stop的  s.state  s.conn  到了RegisterTimer  里面都是0,nil

**Comment by bobohume** [comment]
应该是你没到定时器的时候，连接已经断开了，先前close过了，再到定时器超时关闭的时候自然就不需要close了

**Comment by bobohume** [comment]
1
