### ISSUE TITLE
server config 文件格式

### ISSUE THREAD

**Issue by oxpy** [bobohume/gonet#3]
W2FyZW5hXQ==
c3RhcnRUaW1lICAgICAgICAgICAgICAgICAgICAgICA9IDIwMTEtMTAtMTI=
b3BlbkRheSAgICAgICAgICAgICAgICAgICAgICAgICA9IDE0
Y2xvc2VEYXkgICAgICAgICAgICAgICAgICAgICAgICA9IDc=

WzE5Mi4xNjguMTAuMTM1XQ==
TGluZUlEICAgICAgICAgICAgICAgICAgICAgICAgICA9IDE7
R2F0ZUlEICAgICAgICAgICAgICAgICAgICAgICAgICA9IDE7
TmV0R2F0ZV9XQU5BZGRyZXNzICAgICAgICAgICAgICA9IDE5Mi4xNjguMTAuMTM1OjIxMDAxOw==
TmV0R2F0ZV9XQU5BZGRyZXNzX1NlbmQgICAgICAgICA9IDE5Mi4xNjguMTAuMTM1OjIxMDAxOw==
TmV0R2F0ZV9XQU5DbGllbnRzICAgICAgICAgICAgICA9IDEwMDAwMDs=
TmV0R2F0ZV9MQU5Qb3J0ICAgICAgICAgICAgICAgICA9IDQxMDAxOw==
RGF0YUFnZW50X0xBTlBvcnQgICAgICAgICAgICAgICA9IDYwMDAwOw==
这是什么格式？　
启动 ./server netgate  加载配置文件报错

**Comment by oxpy** [comment]
gonet/base.(*Config).Get2.func1(0x0, 0x0, 0x9ea473, 0x1, 0x0, 0x0, 0x0, 0x0)

**Comment by bobohume** [comment]
这个是加密的，现在cfg没用加密。直接文档打开就行了。考虑linux下，单独工具，暂时不加密

**Comment by oxpy** [comment]
但是现在的SXZ_SERVER.CFG文件好像是加密的

**Comment by oxpy** [comment]
go build 成功后，运行./server netgate 报错　，就是上面那个错误，是不是配置文件不对

**Comment by oxpy** [comment]
请查看一下server目录下面的配置文件，是不是错的

**Comment by squall3322** [comment]
对的，你重新得下代码。 
 
------------------ Original ------------------
From: "oxpy"; 
Date: 2019年4月3日(星期三) 晚上10:39
To: "bobohume/gonet"; 
Cc: "Subscribed"; 
Subject: Re: [bobohume/gonet] server config 文件格式 (#3)

 

请查看一下server目录下面的配置文件，是不是错的
