### ISSUE TITLE
ActorPool.SendMsg中的panic问题

### ISSUE THREAD

**Issue by Xy9310** [bobohume/gonet#6]
在ActorPool.SendMsg中
pActor := this.GetActor(head.Id)
if pActor != nil && pActor.FindCall(funcName) != nil{
	pActor.Send(head, buff)
	return
}
在GetActor后，其他groutine DelActor时
在pActor.Send中，Actor执行过了clear， m_CallChan被close，写入chan 发生panic

**Comment by bobohume** [comment]
it’s safe  acotr 最终调用的是
![image](https://user-images.githubusercontent.com/22991737/91242929-430adb00-e77b-11ea-9525-0ac81dd5a4fc.png)
这里是安全的，信道关闭会recover回去的。
