### ISSUE TITLE
例子都没一个，你是头一回写框架吗？

### ISSUE THREAD

**Issue by AnkoGo123** [bobohume/gonet#9]
例子都没一个，你是头一回写框架吗？

**Comment by buguang01** [comment]
人家不需要例子，只是分享自己的代码。

**Comment by erDong01** [comment]
懂得都自然懂  不懂的最好不要玩这套东西 怕死无葬身之地

**Comment by AnkoGo123** [comment]
> 懂得都自然懂 不懂的最好不要玩这套东西 怕死无葬身之地

我笑了。。。国内程序员看法就是不一样

**Comment by erDong01** [comment]
> > 懂得都自然懂 不懂的最好不要玩这套东西 怕死无葬身之地
> 
> 我笑了。。。国内程序员看法就是不一样

那你是第一天当程序？不知道技术文档都是写一半留一半的

**Comment by AnkoGo123** [comment]
啊哈哈😃，我现在看懂了。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月23日(周二) 上午10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bobohume/gonet] 例子都没一个，你是头一回写框架吗？ (Issue #9)




   
懂得都自然懂 不懂的最好不要玩这套东西 怕死无葬身之地
  
我笑了。。。国内程序员看法就是不一样
  
那你是第一天当程序？不知道技术文档都是写一半留一半的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
